### ISSUE TITLE
Lenght of Reference number cut to 4 characters

### ISSUE THREAD

**Issue by wogri** [dundee/go-qrcode-payment#1]
Hey, thank you for writing qrpay, I like it! 

In https://github.com/dundee/qrpay/blob/fa87d5ef5437f5cf23b2c14d19ae5938c1760d76/epc/epc.go#L62 you cut the number of characters to 4 for the reference. Is there a reason for this? I tried making this 12 or more characters and it still works with my QR Scanner.

Are you accepting a patch?

**Comment by dundee** [comment]
Hi, thanks for noticing! Yes, you are right, this is a bug. It should be either limited to 35 or to 140 chars according to the [reference doc](https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC069-12%20v2.1%20Quick%20Response%20Code%20-%20Guidelines%20to%20Enable%20the%20Data%20Capture%20for%20the%20Initiation%20of%20a%20SCT.pdf).

Feel free to send patch. Thanks!

**Comment by wogri** [comment]
hi, 

Thanks for coming back to me. I can't create a PR in your project and I've already created a fork where I've changed go.mod, etc and I'm using it for a production service, hence I have a hard time sending you a patch. 

You could, however, fix it yourself by going here and changing 4 to 140: https://github.com/dundee/qrpay/blob/fa87d5ef5437f5cf23b2c14d19ae5938c1760d76/epc/epc.go#L63

cheers! 
wogri
